### ISSUE TITLE
Less restrictive license

### ISSUE THREAD

**Issue by jlarmstrongiv** [andywillis/rbg2ase#1]
Have you considered a less restrictive license for rgb2ase?  I’d like to try your library in an app I’m making, but I want to follow all your licensing rules.  

While I am not charging money, I do occasionally receive donations and am technically a company as a freelancer.  So, I do not believe I can use the code under `cc-by-nc-sa`.  Have you considered licensing under just `cc-by` or something more permissive like `mit`?

**Comment by andywillis** [comment]
Hi @jlarmstrongiv

Yes, I can definitely drop the `nc` portion of the license. I'll make the change this week but feel free to use it in the meantime as if I've already done so. Thanks for asking, and for the interest.

A slight warning, however: the core code was written in 2012 and I did a general update a short while ago. But: I don't know if it still works properly since I don't have access to Illustrator any more - the update was more of a guess.

If you could let me know if it works properly for you I'd be grateful. If it doesn't I'll put some work into getting it to work somehow.

**Comment by jlarmstrongiv** [comment]
Hi @andywillis 

> If you could let me know if it works properly for you I'd be grateful. If it doesn't I'll put some work into getting it to work somehow.

Sure, I can test the `.ase` files!  In fact, I just tested https://github.com/1j01/anypalette.js/ which, while working in Adobe PhotoShop and Affinity, fails in Adobe Illustrator and Adobe InDesign.

> Yes, I can definitely drop the nc portion of the license

Thank you!  And the `sa`?  I’d like to keep my code in my preferred license, such as MIT, if possible.  The `cc-sa` and `gpl` variants can be viral and incompatible with other open-source licenses.

**Comment by andywillis** [comment]
Release 1.0.0

- Updated to [a simple CC-BY license](https://creativecommons.org/licenses/by/4.0/).
- Small code fixes/linting.
- Updated README.

https://www.npmjs.com/package/rgb2ase

@jlarmstrongiv

**Comment by jlarmstrongiv** [comment]
Thank you @andywillis 🎉 I can confirm that the `Mordred.ase` generated by cloning this repo and running the example works with Affinity software, as well as Adobe Illustrator, InDesign, and PhotoShop
